# Generated by Django 4.2.2 on 2023-10-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collegerecomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('location', models.CharField(default=None, max_length=100, null=True)),
                ('degree_level', models.CharField(default=None, max_length=200, null=True)),
                ('collegelink', models.CharField(default=None, max_length=100, null=True)),
                ('tuition_fee', models.FloatField(default=None, max_length=100, null=True)),
                ('minimum_score', models.FloatField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
