# Generated by Django 4.2.2 on 2023-10-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoysCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('location', models.CharField(default=None, max_length=100, null=True)),
                ('degree_level', models.CharField(default=None, max_length=200, null=True)),
                ('collegelink', models.CharField(default=None, max_length=100, null=True)),
                ('minimum_score', models.FloatField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GirlsCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('location', models.CharField(default=None, max_length=100, null=True)),
                ('degree_level', models.CharField(default=None, max_length=200, null=True)),
                ('collegelink', models.CharField(default=None, max_length=100, null=True)),
                ('minimum_score', models.FloatField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
