# Generated by Django 4.2.2 on 2023-10-23 06:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_boyscollege_girlscollege'),
    ]

    operations = [
        migrations.AddField(
            model_name='boyscollege',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='girlscollege',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
