# Generated by Django 4.2.2 on 2023-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0003_alter_postd_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postd',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
    ]
