# Generated by Django 4.2.2 on 2023-09-08 10:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0005_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
