# Generated by Django 4.2.2 on 2023-09-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0006_alter_college_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postd',
            name='subjectchemistry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postd',
            name='subjectenglish',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postd',
            name='subjectislmaic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postd',
            name='subjectmath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postd',
            name='subjectpakstudy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postd',
            name='subjectphyics',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postd',
            name='subjecturdu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
