# Generated by Django 4.2.2 on 2023-09-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegepost',
            name='meritCOM',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='collegepost',
            name='meritFSCE',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='collegepost',
            name='meritFSCM',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='collegepost',
            name='meritICSC',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='collegepost',
            name='meritICSE',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='collegepost',
            name='meritICSS',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
