# Generated by Django 4.2.2 on 2023-09-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgpost', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegepost',
            name='collegelink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
